#自定义配置
bomu:
  tempPath: D:/apache-tomcat-7.0.70/webapps/upload/bomu-game
  upload:
    url: D:/apache-tomcat-7.0.70/webapps/upload/bomu-game

server:
  port: 8088
  tomcat: # 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
    basedir: ${bomu.tempPath}

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: ${bomu.upload.url}
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3307/manage?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useAffectedRows=true
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 30000
      validation-query: select 'x' FROM DUAL
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 50
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1


